SRCS += \
	src/atm.cpp \
	src/business_client.cpp \
	src/cdm.cpp \
	src/client_interface.cpp \
	src/client_list.cpp \
	src/client.cpp \
	src/data_interface.cpp \
	src/data.cpp \
	src/debt_exception.cpp \
	src/deposit.cpp \
	src/desk_interface.cpp \
	src/desk_list.cpp \
	src/desk.cpp \
	src/employee_interface.cpp \
	src/employee_list.cpp \
	src/employee.cpp \
	src/failed_to_open_exception.cpp \
	src/handout.cpp \
	src/individual_client.cpp \
	src/same_client_exception.cpp \
	src/service_interface.cpp \
	src/service.cpp \
	src/simulation_interface.cpp \
	src/simulation.cpp \
	src/transfer.cpp \
	src/unable_to_save_exception.cpp \
	src/wrong_machine_exception.cpp